# Uncomment the next line to define a global platform for your project
# source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'PixeliteCli' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PixeliteCli
  pod 'RSKImageCropper'
  pod 'QBImagePickerController'

end
